# Generated by Django 5.1.4 on 2025-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='id',
        ),
        migrations.AddField(
            model_name='employee_data',
            name='EmployeeId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
